name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.9.0
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: npm run setup

      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Build
        run: npm run buildinfo

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "internalerror_-storageexpansion-${{ steps.package-version.outputs.current-version}}"
          path: "./dist/internalerror_-storageexpansion-${{ steps.package-version.outputs.current-version}}.zip"

      - name: Increment Version
        run: |
          git config --global user.email "phil.gatzka@gmail.com"
          git config --global user.name "Github Actions"
          npm version patch